// Tarot Card Data - INTARIUS
// 78 cards with reversed meanings
// Images from sacred-texts.com (reliable CDN)

const MAJOR_ARCANA = [
    { id: 0, name: "0. The Fool", narrative: "сделать смелый шаг в неизвестность", element: "air", keywords: ["начало", "свобода", "риск", "потенциал"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar00.jpg", short: "Новое начало, свобода духа", full: "Знаешь это чувство, когда хочется всё бросить и начать с нуля? Шут — именно об этом. Ты стоишь на краю чего-то нового, и да, немного страшно. Но внутри тебя живёт ребёнок, который верит в чудеса.", advice: "Рискни. Прыгни. Сетка появится.", reversedShort: "Безрассудство, наивность", reversedFull: "Ты слишком легкомысленно относишься к ситуации. Пора остановиться и подумать перед прыжком.", reversedAdvice: "Не рискуй вслепую." },
    { id: 1, name: "I. The Magician", narrative: "взять инициативу в свои руки", element: "air", keywords: ["воля", "мастерство", "действие", "ресурсы"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar01.jpg", short: "Мастерство, сила воли", full: "У тебя есть всё, чтобы сотворить чудо. Маг говорит: 'Ты — творец своей реальности'. Все инструменты разложены перед тобой.", advice: "Действуй. Всё в твоих руках.", reversedShort: "Манипуляция, обман", reversedFull: "Кто-то использует свои таланты не по назначению. Возможен обман или самообман.", reversedAdvice: "Проверь свои мотивы." },
    { id: 2, name: "II. The High Priestess", narrative: "довериться скрытой интуиции", element: "water", keywords: ["интуиция", "тайна", "пассивность", "знание"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar02.jpg", short: "Интуиция, тайное знание", full: "Тсс... Слышишь? Это твой внутренний голос. Жрица просит выключить логику и послушать тишину.", advice: "Слушай интуицию, а не логику.", reversedShort: "Скрытые мотивы, блокировка", reversedFull: "Ты игнорируешь свою интуицию или не доверяешь ей. Возможно, кто-то скрывает правду.", reversedAdvice: "Прислушайся к внутреннему голосу." },
    { id: 3, name: "III. The Empress", narrative: "раскрыть творческий потенциал", element: "earth", keywords: ["изобилие", "творчество", "рост", "плодородие"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar03.jpg", short: "Изобилие, творчество", full: "Жизнь бьёт ключом! Это время расцвета, красоты и удовольствий.", advice: "Твори и наслаждайся жизнью.", reversedShort: "Застой, зависимость", reversedFull: "Творческий блок или чрезмерная зависимость от комфорта. Пора выйти из зоны комфорта.", reversedAdvice: "Перестань откладывать." },
    { id: 4, name: "IV. The Emperor", narrative: "навести порядок и взять контроль", element: "fire", keywords: ["власть", "структура", "порядок", "контроль"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar04.jpg", short: "Власть, структура", full: "Пора навести порядок. Хватит хаоса! Император требует дисциплины и чёткого плана.", advice: "Возьми ответственность на себя.", reversedShort: "Тирания, хаос", reversedFull: "Слишком жёсткий контроль или полное его отсутствие. Баланс нарушен.", reversedAdvice: "Смягчи хватку или возьми себя в руки." },
    { id: 5, name: "V. The Hierophant", narrative: "следовать проверенным традициям", element: "earth", keywords: ["традиция", "обучение", "мораль", "наставник"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar05.jpg", short: "Традиции, обучение", full: "Иногда нужно следовать правилам. Иерофант — это мудрый учитель или наставник.", advice: "Следуй правилам и учись.", reversedShort: "Бунт, свобода от догм", reversedFull: "Пора нарушить правила и найти свой путь. Традиции тебя душат.", reversedAdvice: "Доверься своему пути." },
    { id: 6, name: "VI. The Lovers", narrative: "сделать выбор сердцем", element: "air", keywords: ["выбор", "любовь", "союз", "гармония"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar06.jpg", short: "Любовь, важный выбор", full: "Это не только про романтику. Это про ВЫБОР. Выбор сердцем.", advice: "Выбирай сердцем.", reversedShort: "Дисгармония, плохой выбор", reversedFull: "Конфликт ценностей или неверный выбор. Возможно, ты идёшь против себя.", reversedAdvice: "Пересмотри свои приоритеты." },
    { id: 7, name: "VII. The Chariot", narrative: "двигаться к цели несмотря ни на что", element: "water", keywords: ["победа", "движение", "прорыв", "контроль"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar07.jpg", short: "Победа, движение вперёд", full: "Газ в пол! Никаких сомнений. Ты взял поводья в свои руки, и теперь только вперёд.", advice: "Двигайся к цели, не останавливайся.", reversedShort: "Потеря контроля", reversedFull: "Ты теряешь управление ситуацией. Слишком много сил уходит впустую.", reversedAdvice: "Притормози и перегруппируйся." },
    { id: 8, name: "VIII. Strength", narrative: "проявить мягкую, но твердую силу", element: "fire", keywords: ["сила", "терпение", "смелость", "страсть"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar08.jpg", short: "Внутренняя сила, терпение", full: "Настоящая сила не в мускулах, а в мягкости. Ты можешь укротить своего внутреннего льва любовью.", advice: "Будь мягче, но увереннее.", reversedShort: "Слабость, сомнения", reversedFull: "Ты сомневаешься в себе или поддаёшься страхам. Вспомни о своей внутренней силе.", reversedAdvice: "Поверь в себя." },
    { id: 9, name: "IX. The Hermit", narrative: "уйти в себя для поиска ответов", element: "earth", keywords: ["поиск", "одиночество", "мудрость", "анализ"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar09.jpg", short: "Поиск себя, мудрость", full: "Выключи телефон. Закрой дверь. Тебе нужно побыть одному.", advice: "Найди время для тишины.", reversedShort: "Изоляция, застой", reversedFull: "Ты слишком замкнулся в себе. Пора выходить в мир и делиться своим светом.", reversedAdvice: "Не прячься от людей." },
    { id: 10, name: "X. Wheel of Fortune", narrative: "довериться циклу перемен", element: "fire", keywords: ["удача", "перемены", "судьба", "цикл"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar10.jpg", short: "Удача, перемены", full: "Всё меняется! Сегодня ты наверху, завтра... кто знает? Но сейчас Колесо крутится в твою пользу.", advice: "Доверься переменам. Всё к лучшему.", reversedShort: "Неудача, сопротивление", reversedFull: "Колесо повернулось против тебя. Но это временно — готовься к новому подъёму.", reversedAdvice: "Это пройдёт. Держись." },
    { id: 11, name: "XI. Justice", narrative: "взвесить всё и принять честное решение", element: "air", keywords: ["правда", "закон", "баланс", "решение"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar11.jpg", short: "Честность, ответственность", full: "Что посеешь, то и пожнёшь. Справедливость требует честности — перед собой и другими.", advice: "Будь честен и объективен.", reversedShort: "Несправедливость, обман", reversedFull: "Кто-то ведёт нечестную игру. Возможно, это ты сам избегаешь ответственности.", reversedAdvice: "Признай свою ошибку." },
    { id: 12, name: "XII. The Hanged Man", narrative: "посмотреть на вещи под другим углом", element: "water", keywords: ["жертва", "пауза", "новый взгляд", "ожидание"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar12.jpg", short: "Взгляни иначе", full: "Застрял? Повешенный советует: переверни картинку. Посмотри на ситуацию иначе.", advice: "Отпусти. Позволь жизни течь.", reversedShort: "Упрямство, застой", reversedFull: "Ты упорно цепляешься за старый взгляд, хотя он не работает.", reversedAdvice: "Попробуй по-другому." },
    { id: 13, name: "XIII. Death", narrative: "отпустить старое ради нового", element: "water", keywords: ["конец", "трансформация", "переход", "обновление"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar13.jpg", short: "Конец и начало", full: "Не пугайся! Это про то, что что-то отжило своё. Отпусти, чтобы пришло новое.", advice: "Попрощайся с прошлым.", reversedShort: "Сопротивление переменам", reversedFull: "Ты держишься за то, что пора отпустить. Страх перемен тормозит тебя.", reversedAdvice: "Отпусти. Это необходимо." },
    { id: 14, name: "XIV. Temperance", narrative: "найти гармонию и золотую середину", element: "fire", keywords: ["баланс", "исцеление", "терпение", "синтез"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar14.jpg", short: "Баланс — это искусство", full: "Умеренность напоминает: крайности разрушают. Найди золотую середину.", advice: "Не впадай в крайности.", reversedShort: "Дисбаланс, излишества", reversedFull: "Ты нарушил баланс — слишком много или слишком мало чего-то важного.", reversedAdvice: "Восстанови равновесие." },
    { id: 15, name: "XV. The Devil", narrative: "осознать свои зависимости", element: "earth", keywords: ["зависимость", "материализм", "искушение", "страх"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar15.jpg", short: "Цепи иллюзий", full: "Чувствуешь себя в ловушке? Посмотри на свои 'цепи' — они свободно висят.", advice: "Освободи себя.", reversedShort: "Освобождение", reversedFull: "Ты наконец осознаёшь свои зависимости и готов от них избавиться.", reversedAdvice: "Беги из этой ловушки!" },
    { id: 16, name: "XVI. The Tower", narrative: "пережить резкое очищение", element: "fire", keywords: ["крах", "разрушение", "шок", "освобождение"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar16.jpg", short: "Гроза очищает", full: "Больно? Да. Но Башня рушится, чтобы ты увидел правду.", advice: "Не держись за то, что падает.", reversedShort: "Избежание краха", reversedFull: "Ты либо избежал катастрофы, либо затягиваешь неизбежное разрушение.", reversedAdvice: "Иногда лучше разрушить самому." },
    { id: 17, name: "XVII. The Star", narrative: "обрести надежду и вдохновение", element: "air", keywords: ["надежда", "вдохновение", "исцеление", "вера"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar17.jpg", short: "Надежда светит", full: "После тёмной ночи всегда выходят звёзды. Вселенная посылает знак: всё будет хорошо.", advice: "Не теряй надежду.", reversedShort: "Потеря веры", reversedFull: "Ты потерял надежду или веру в себя. Свет есть, просто ты его не видишь.", reversedAdvice: "Подними глаза к небу." },
    { id: 18, name: "XVIII. The Moon", narrative: "пройти сквозь туман иллюзий", element: "water", keywords: ["иллюзия", "страх", "подсознание", "сны"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar18.jpg", short: "Не всё так, как кажется", full: "В лунном свете всё выглядит иначе. Не доверяй первому впечатлению.", advice: "Будь осторожен с иллюзиями.", reversedShort: "Прояснение", reversedFull: "Туман рассеивается, страхи отступают. Ты начинаешь видеть правду.", reversedAdvice: "Доверься ясности." },
    { id: 19, name: "XIX. The Sun", narrative: "насладиться ясностью и успехом", element: "fire", keywords: ["радость", "успех", "энергия", "ясность"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar19.jpg", short: "Радость и победа!", full: "Это лучшая карта! Солнце сияет, всё получается. Наслаждайся!", advice: "Сияй!", reversedShort: "Временные тучи", reversedFull: "Радость приглушена, но солнце всё ещё там. Скоро тучи разойдутся.", reversedAdvice: "Не унывай, это временно." },
    { id: 20, name: "XX. Judgement", narrative: "ответить на призыв судьбы", element: "fire", keywords: ["возрождение", "призыв", "прощение", "судьба"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar20.jpg", short: "Время пробуждения", full: "Слышишь? Это труба зовёт тебя. Пора проснуться и ответить на свой призыв.", advice: "Прислушайся к внутреннему голосу.", reversedShort: "Игнорирование призыва", reversedFull: "Ты отказываешься слышать свой призыв или не можешь простить себя.", reversedAdvice: "Прости себя и двигайся дальше." },
    { id: 21, name: "XXI. The World", narrative: "достичь полной гармонии", element: "earth", keywords: ["завершение", "целостность", "путешествие", "успех"], image: "https://www.sacred-texts.com/tarot/pkt/img/ar21.jpg", short: "Ты дошёл до финиша", full: "Поздравляю! Цикл завершён, цель достигнута, круг замкнулся.", advice: "Празднуй!", reversedShort: "Незавершённость", reversedFull: "Что-то мешает завершить цикл. Осталась небольшая деталь.", reversedAdvice: "Доведи дело до конца." }
];

const MINOR_ARCANA = [
    // Wands (Fire)
    { id: 22, name: "Ace of Wands", element: "fire", keywords: ["импульс", "страсть", "начало"], image: "https://www.sacred-texts.com/tarot/pkt/img/waac.jpg", short: "Вдохновение, новая идея", full: "Искра творчества и мощный импульс энергии.", advice: "Действуйте смело!", reversedShort: "Задержка, нехватка энергии", reversedFull: "Идея есть, но сил на её реализацию пока нет.", reversedAdvice: "Подождите подходящего момента." },
    { id: 23, name: "Two of Wands", element: "fire", keywords: ["план", "выбор", "перспектива"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa02.jpg", short: "Планирование, выбор", full: "Вы стоите на пороге. Весь мир перед вами.", advice: "Продумайте стратегию.", reversedShort: "Страх перемен", reversedFull: "Вы боитесь сделать первый шаг.", reversedAdvice: "Не откладывайте решение." },
    { id: 24, name: "Three of Wands", element: "fire", keywords: ["рост", "успех", "расширение"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa03.jpg", short: "Первые успехи", full: "Ваши корабли возвращаются с золотом.", advice: "Смотрите шире.", reversedShort: "Задержки", reversedFull: "Результаты запаздывают.", reversedAdvice: "Проявите терпение." },
    { id: 25, name: "Four of Wands", element: "fire", keywords: ["праздник", "дом", "стабильность"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa04.jpg", short: "Праздник, стабильность", full: "Время радости и празднования.", advice: "Отпразднуйте успехи.", reversedShort: "Неудовлетворённость", reversedFull: "Чего-то не хватает в вашем 'раю'.", reversedAdvice: "Ищите истинный источник радости." },
    { id: 26, name: "Five of Wands", element: "fire", keywords: ["конфликт", "соревнование"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa05.jpg", short: "Конкуренция, борьба", full: "Столкновение интересов, споры.", advice: "Докажите своё мастерство.", reversedShort: "Избегание конфликта", reversedFull: "Вы уклоняетесь от честной борьбы.", reversedAdvice: "Иногда надо отстаивать себя." },
    { id: 27, name: "Six of Wands", element: "fire", keywords: ["победа", "признание"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa06.jpg", short: "Победа, признание", full: "Вы — победитель. Общественное признание.", advice: "Примите похвалу.", reversedShort: "Провал, критика", reversedFull: "Успех ускользает или вас критикуют.", reversedAdvice: "Учитесь на ошибках." },
    { id: 28, name: "Seven of Wands", element: "fire", keywords: ["защита", "стойкость"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa07.jpg", short: "Защита, стойкость", full: "Вы на вершине, но многие хотят ваше место.", advice: "Не сдавайте позиций.", reversedShort: "Сдача позиций", reversedFull: "Вы устали защищаться.", reversedAdvice: "Возможно, пора отступить." },
    { id: 29, name: "Eight of Wands", element: "fire", keywords: ["скорость", "новости"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa08.jpg", short: "Скорость, новости", full: "События развиваются стремительно.", advice: "Действуйте быстро.", reversedShort: "Задержки", reversedFull: "Новости запаздывают.", reversedAdvice: "Запаситесь терпением." },
    { id: 30, name: "Nine of Wands", element: "fire", keywords: ["усталость", "бдительность"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa09.jpg", short: "Усталость, оборона", full: "Битва была долгой. Остался последний рывок.", advice: "Не сдавайтесь.", reversedShort: "Паранойя, истощение", reversedFull: "Вы слишком настороже.", reversedAdvice: "Позвольте себе расслабиться." },
    { id: 31, name: "Ten of Wands", element: "fire", keywords: ["тяжесть", "ответственность"], image: "https://www.sacred-texts.com/tarot/pkt/img/wa10.jpg", short: "Бремя", full: "Вы взвалили слишком много.", advice: "Делегируйте.", reversedShort: "Сброс груза", reversedFull: "Вы наконец избавляетесь от лишнего.", reversedAdvice: "Продолжайте упрощать." },
    { id: 32, name: "Page of Wands", element: "fire", keywords: ["весть", "энтузиазм"], image: "https://www.sacred-texts.com/tarot/pkt/img/wapa.jpg", short: "Энтузиазм, весть", full: "Юношеский задор и хорошие новости.", advice: "Будьте открыты.", reversedShort: "Плохие новости", reversedFull: "Задержка или разочарование.", reversedAdvice: "Не теряйте веру." },
    { id: 33, name: "Knight of Wands", element: "fire", keywords: ["действие", "страсть"], image: "https://www.sacred-texts.com/tarot/pkt/img/wakn.jpg", short: "Импульсивность", full: "Огонь действия, сметающий преграды.", advice: "Направьте энергию.", reversedShort: "Поспешность, агрессия", reversedFull: "Слишком быстро и необдуманно.", reversedAdvice: "Притормозите." },
    { id: 34, name: "Queen of Wands", element: "fire", keywords: ["харизма", "уверенность"], image: "https://www.sacred-texts.com/tarot/pkt/img/waqu.jpg", short: "Харизма", full: "Яркая, независимая женщина-лидер.", advice: "Верьте в себя.", reversedShort: "Ревность, эгоизм", reversedFull: "Уверенность переходит в высокомерие.", reversedAdvice: "Будьте скромнее." },
    { id: 35, name: "King of Wands", element: "fire", keywords: ["лидер", "видение"], image: "https://www.sacred-texts.com/tarot/pkt/img/waki.jpg", short: "Лидерство", full: "Зрелый лидер-вдохновитель.", advice: "Возьмите руководство.", reversedShort: "Тиран", reversedFull: "Лидерство становится деспотизмом.", reversedAdvice: "Слушайте других." },

    // Cups (Water)
    { id: 36, name: "Ace of Cups", element: "water", keywords: ["любовь", "эмоции"], image: "https://www.sacred-texts.com/tarot/pkt/img/cuac.jpg", short: "Любовь, изобилие чувств", full: "Чаша переполняется эмоциями.", advice: "Откройте сердце.", reversedShort: "Эмоциональная блокировка", reversedFull: "Вы закрыты для любви.", reversedAdvice: "Разрешите себе чувствовать." },
    { id: 37, name: "Two of Cups", element: "water", keywords: ["союз", "партнерство"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu02.jpg", short: "Партнерство", full: "Идеальная пара, гармония.", advice: "Ищите единство.", reversedShort: "Разлад", reversedFull: "Дисгармония в отношениях.", reversedAdvice: "Поговорите честно." },
    { id: 38, name: "Three of Cups", element: "water", keywords: ["праздник", "дружба"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu03.jpg", short: "Праздник, дружба", full: "Радость в кругу друзей.", advice: "Разделите радость.", reversedShort: "Излишества", reversedFull: "Праздник зашёл слишком далеко.", reversedAdvice: "Знайте меру." },
    { id: 39, name: "Four of Cups", element: "water", keywords: ["апатия", "скука"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu04.jpg", short: "Скука, пресыщение", full: "Вы не замечаете возможностей.", advice: "Оглянитесь вокруг.", reversedShort: "Мотивация возвращается", reversedFull: "Вы выходите из апатии.", reversedAdvice: "Хватайте шанс!" },
    { id: 40, name: "Five of Cups", element: "water", keywords: ["потеря", "печаль"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu05.jpg", short: "Разочарование", full: "Скорбь над потерями.", advice: "Цените то, что осталось.", reversedShort: "Принятие потери", reversedFull: "Вы начинаете отпускать боль.", reversedAdvice: "Двигайтесь вперёд." },
    { id: 41, name: "Six of Cups", element: "water", keywords: ["прошлое", "ностальгия"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu06.jpg", short: "Ностальгия", full: "Воспоминания о прошлом.", advice: "Ищите радость в простом.", reversedShort: "Застревание в прошлом", reversedFull: "Вы не можете отпустить прошлое.", reversedAdvice: "Живите настоящим." },
    { id: 42, name: "Seven of Cups", element: "water", keywords: ["иллюзия", "мечты"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu07.jpg", short: "Иллюзии, мечты", full: "Много вариантов, но большинство — миражи.", advice: "Спуститесь на землю.", reversedShort: "Прозрение", reversedFull: "Иллюзии развеяны.", reversedAdvice: "Действуйте на практике." },
    { id: 43, name: "Eight of Cups", element: "water", keywords: ["уход", "поиск"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu08.jpg", short: "Уход", full: "Отказ от того, что не радует.", advice: "Идите туда, где лучше.", reversedShort: "Страх уйти", reversedFull: "Вы боитесь оставить несчастье.", reversedAdvice: "Сделайте шаг." },
    { id: 44, name: "Nine of Cups", element: "water", keywords: ["желание", "счастье"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu09.jpg", short: "Исполнение желаний", full: "Удовлетворение и комфорт.", advice: "Наслаждайтесь.", reversedShort: "Жадность", reversedFull: "Вам всё мало.", reversedAdvice: "Оцените имеющееся." },
    { id: 45, name: "Ten of Cups", element: "water", keywords: ["семья", "гармония"], image: "https://www.sacred-texts.com/tarot/pkt/img/cu10.jpg", short: "Семейное счастье", full: "Абсолютная гармония.", advice: "Цените близких.", reversedShort: "Семейный разлад", reversedFull: "Конфликт в семье.", reversedAdvice: "Работайте над отношениями." },
    { id: 46, name: "Page of Cups", element: "water", keywords: ["весть", "чувства"], image: "https://www.sacred-texts.com/tarot/pkt/img/cupa.jpg", short: "Романтическая весть", full: "Нежное послание.", advice: "Доверьтесь интуиции.", reversedShort: "Незрелые эмоции", reversedFull: "Инфантильность в чувствах.", reversedAdvice: "Повзрослейте эмоционально." },
    { id: 47, name: "Knight of Cups", element: "water", keywords: ["романтика", "идеал"], image: "https://www.sacred-texts.com/tarot/pkt/img/cukn.jpg", short: "Романтика", full: "Принц на белом коне.", advice: "Следуйте за сердцем.", reversedShort: "Обман, неверность", reversedFull: "Красивые слова без дел.", reversedAdvice: "Проверяйте действия." },
    { id: 48, name: "Queen of Cups", element: "water", keywords: ["сострадание", "интуиция"], image: "https://www.sacred-texts.com/tarot/pkt/img/cuqu.jpg", short: "Эмпатия", full: "Глубоко чувствующая женщина.", advice: "Проявите сострадание.", reversedShort: "Эмоциональная нестабильность", reversedFull: "Чувства захлёстывают.", reversedAdvice: "Найдите баланс." },
    { id: 49, name: "King of Cups", element: "water", keywords: ["баланс", "мудрость"], image: "https://www.sacred-texts.com/tarot/pkt/img/cuki.jpg", short: "Эмоциональный контроль", full: "Мудрый советник.", advice: "Сохраняйте спокойствие.", reversedShort: "Эмоциональная манипуляция", reversedFull: "Использование чувств в своих целях.", reversedAdvice: "Будьте честны." },

    // Swords (Air)
    { id: 50, name: "Ace of Swords", element: "air", keywords: ["ясность", "правда"], image: "https://www.sacred-texts.com/tarot/pkt/img/swac.jpg", short: "Ясность, прорыв", full: "Триумф разума.", advice: "Режьте правду.", reversedShort: "Путаница", reversedFull: "Мысли запутаны.", reversedAdvice: "Проясните ситуацию." },
    { id: 51, name: "Two of Swords", element: "air", keywords: ["выбор", "тупик"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw02.jpg", short: "Тупик", full: "Нежелание видеть правду.", advice: "Снимите повязку.", reversedShort: "Перегрузка информацией", reversedFull: "Слишком много данных.", reversedAdvice: "Упростите." },
    { id: 52, name: "Three of Swords", element: "air", keywords: ["боль", "разлука"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw03.jpg", short: "Разбитое сердце", full: "Боль и печаль.", advice: "Проживите и отпустите.", reversedShort: "Исцеление", reversedFull: "Боль начинает утихать.", reversedAdvice: "Позвольте себе исцелиться." },
    { id: 53, name: "Four of Swords", element: "air", keywords: ["покой", "пауза"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw04.jpg", short: "Отдых", full: "Пауза для восстановления.", advice: "Возьмите тайм-аут.", reversedShort: "Выгорание", reversedFull: "Вы не даёте себе отдыха.", reversedAdvice: "Остановитесь немедленно." },
    { id: 54, name: "Five of Swords", element: "air", keywords: ["конфликт", "эго"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw05.jpg", short: "Пиррова победа", full: "Победа, не приносящая радости.", advice: "Стоит ли игра свеч?", reversedShort: "Примирение", reversedFull: "Конфликт разрешается.", reversedAdvice: "Протяните руку." },
    { id: 55, name: "Six of Swords", element: "air", keywords: ["переход", "путь"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw06.jpg", short: "Переход", full: "Уход к тихому берегу.", advice: "Двигайтесь к спокойствию.", reversedShort: "Застревание", reversedFull: "Не можете уйти от проблем.", reversedAdvice: "Сделайте первый шаг." },
    { id: 56, name: "Seven of Swords", element: "air", keywords: ["хитрость", "обман"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw07.jpg", short: "Хитрость", full: "Действие исподтишка.", advice: "Будьте осторожны.", reversedShort: "Разоблачение", reversedFull: "Обман раскрыт.", reversedAdvice: "Говорите правду." },
    { id: 57, name: "Eight of Swords", element: "air", keywords: ["плен", "страх"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw08.jpg", short: "Ограничения", full: "Барьеры в голове.", advice: "Освободитесь от страхов.", reversedShort: "Освобождение", reversedFull: "Вы снимаете повязку.", reversedAdvice: "Вы свободны!" },
    { id: 58, name: "Nine of Swords", element: "air", keywords: ["страх", "тревога"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw09.jpg", short: "Кошмар", full: "Бессонные ночи от страхов.", advice: "Не накручивайте.", reversedShort: "Облегчение", reversedFull: "Страхи отступают.", reversedAdvice: "Выдохните." },
    { id: 59, name: "Ten of Swords", element: "air", keywords: ["конец", "дно"], image: "https://www.sacred-texts.com/tarot/pkt/img/sw10.jpg", short: "Финал", full: "Хуже уже не будет.", advice: "Вставайте.", reversedShort: "Возрождение", reversedFull: "Начало восстановления.", reversedAdvice: "Новый день." },
    { id: 60, name: "Page of Swords", element: "air", keywords: ["ум", "любопытство"], image: "https://www.sacred-texts.com/tarot/pkt/img/swpa.jpg", short: "Новости", full: "Острый ум, но и сплетни.", advice: "Анализируйте.", reversedShort: "Сплетни", reversedFull: "Злые языки.", reversedAdvice: "Не слушайте." },
    { id: 61, name: "Knight of Swords", element: "air", keywords: ["скорость", "натиск"], image: "https://www.sacred-texts.com/tarot/pkt/img/swkn.jpg", short: "Агрессия", full: "Стремительное действие.", advice: "Не рубите с плеча.", reversedShort: "Безрассудство", reversedFull: "Опасная поспешность.", reversedAdvice: "Подумайте сначала." },
    { id: 62, name: "Queen of Swords", element: "air", keywords: ["правда", "ясность"], image: "https://www.sacred-texts.com/tarot/pkt/img/swqu.jpg", short: "Независимость", full: "Острый ум и язык.", advice: "Думайте головой.", reversedShort: "Жестокость", reversedFull: "Правда ранит.", reversedAdvice: "Смягчите тон." },
    { id: 63, name: "King of Swords", element: "air", keywords: ["власть", "логика"], image: "https://www.sacred-texts.com/tarot/pkt/img/swki.jpg", short: "Логика, власть", full: "Решения на фактах.", advice: "Будьте беспристрастны.", reversedShort: "Тирания ума", reversedFull: "Холодная жестокость.", reversedAdvice: "Включите сердце." },

    // Pentacles (Earth)
    { id: 64, name: "Ace of Pentacles", element: "earth", keywords: ["деньги", "шанс"], image: "https://www.sacred-texts.com/tarot/pkt/img/peac.jpg", short: "Шанс, деньги", full: "Дар небес, возможность заработать.", advice: "Ловите удачу.", reversedShort: "Упущенный шанс", reversedFull: "Возможность ускользает.", reversedAdvice: "Не упустите." },
    { id: 65, name: "Two of Pentacles", element: "earth", keywords: ["баланс", "гибкость"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe02.jpg", short: "Гибкость", full: "Жонглирование обязанностями.", advice: "Будьте гибче.", reversedShort: "Перегрузка", reversedFull: "Слишком много дел.", reversedAdvice: "Сократите список." },
    { id: 66, name: "Three of Pentacles", element: "earth", keywords: ["команда", "мастерство"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe03.jpg", short: "Мастерство", full: "Командная работа.", advice: "Сотрудничайте.", reversedShort: "Некомпетентность", reversedFull: "Качество страдает.", reversedAdvice: "Улучшайте навыки." },
    { id: 67, name: "Four of Pentacles", element: "earth", keywords: ["жадность", "контроль"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe04.jpg", short: "Жадность", full: "Страх потери.", advice: "Не будьте скрягой.", reversedShort: "Щедрость", reversedFull: "Вы отпускаете хватку.", reversedAdvice: "Делитесь." },
    { id: 68, name: "Five of Pentacles", element: "earth", keywords: ["нужда", "кризис"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe05.jpg", short: "Нужда", full: "Финансовые потери.", advice: "Просите помощь.", reversedShort: "Выход из кризиса", reversedFull: "Ситуация улучшается.", reversedAdvice: "Держитесь курса." },
    { id: 69, name: "Six of Pentacles", element: "earth", keywords: ["помощь", "щедрость"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe06.jpg", short: "Щедрость", full: "Баланс давать-брать.", advice: "Будьте щедры.", reversedShort: "Долги", reversedFull: "Дисбаланс в обмене.", reversedAdvice: "Выровняйте счёт." },
    { id: 70, name: "Seven of Pentacles", element: "earth", keywords: ["терпение", "урожай"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe07.jpg", short: "Ожидание урожая", full: "Нужно ждать результатов.", advice: "Не торопите.", reversedShort: "Нетерпение", reversedFull: "Вы хотите всё и сразу.", reversedAdvice: "Терпение." },
    { id: 71, name: "Eight of Pentacles", element: "earth", keywords: ["труд", "навык"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe08.jpg", short: "Труд, навыки", full: "Усердная работа.", advice: "Совершенствуйтесь.", reversedShort: "Халтура", reversedFull: "Качество падает.", reversedAdvice: "Работайте усерднее." },
    { id: 72, name: "Nine of Pentacles", element: "earth", keywords: ["роскошь", "успех"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe09.jpg", short: "Достаток", full: "Финансовая независимость.", advice: "Побалуйте себя.", reversedShort: "Зависимость", reversedFull: "Вы живёте за чужой счёт.", reversedAdvice: "Станьте независимым." },
    { id: 73, name: "Ten of Pentacles", element: "earth", keywords: ["семья", "наследие"], image: "https://www.sacred-texts.com/tarot/pkt/img/pe10.jpg", short: "Богатство, наследие", full: "Семейный капитал.", advice: "Думайте о будущем.", reversedShort: "Семейные споры", reversedFull: "Конфликт из-за денег.", reversedAdvice: "Семья важнее." },
    { id: 74, name: "Page of Pentacles", element: "earth", keywords: ["шанс", "ученик"], image: "https://www.sacred-texts.com/tarot/pkt/img/pepa.jpg", short: "Ученик", full: "Новое начинание в бизнесе.", advice: "Учитесь.", reversedShort: "Лень", reversedFull: "Нет мотивации учиться.", reversedAdvice: "Займитесь делом." },
    { id: 75, name: "Knight of Pentacles", element: "earth", keywords: ["труд", "упорство"], image: "https://www.sacred-texts.com/tarot/pkt/img/pekn.jpg", short: "Надёжность", full: "Медленное, но верное движение.", advice: "Тише едешь — дальше будешь.", reversedShort: "Застой", reversedFull: "Слишком медленно.", reversedAdvice: "Ускорьтесь." },
    { id: 76, name: "Queen of Pentacles", element: "earth", keywords: ["хозяйка", "забота"], image: "https://www.sacred-texts.com/tarot/pkt/img/pequ.jpg", short: "Хозяйка", full: "Умелое ведение дел.", advice: "Заботьтесь о комфорте.", reversedShort: "Трудоголизм", reversedFull: "Работа съедает жизнь.", reversedAdvice: "Найдите баланс." },
    { id: 77, name: "King of Pentacles", element: "earth", keywords: ["босс", "бизнес"], image: "https://www.sacred-texts.com/tarot/pkt/img/peki.jpg", short: "Бизнесмен", full: "Вершина успеха.", advice: "Управляйте мудро.", reversedShort: "Жадность", reversedFull: "Деньги важнее всего.", reversedAdvice: "Помните о ценностях." }
];

const FULL_DECK = [...MAJOR_ARCANA, ...MINOR_ARCANA];
